steps:
  - label: ":pipeline: Launch Documentation Builds"
    command: buildkite-agent pipeline upload .buildkite/documentation.yml
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true
