pages = [
    "ReservoirComputing.jl" => "index.md",
    "Tutorials" => Any[
        "Building a model from scratch" => "tutorials/scratch.md",
        "Chaos forecasting with an ESN" => "tutorials/lorenz_basic.md",
        #"Using Different Training Methods" => "esn_tutorials/different_training.md",
        "Deep Echo State Networks" => "tutorials/deep_esn.md",
        #"Hybrid Echo State Networks" => "tutorials/hybrid.md",
        "Reservoir Computing with Cellular Automata" => "tutorials/reca.md"],
    "API Documentation" => Any[
        "Layers" => "api/layers.md",
        "Models" => "api/models.md",
        "Utilities" => "api/utils.md",
        "Train" => "api/train.md",
        "Predict" => "api/predict.md",
        "States" => "api/states.md",
        "Initializers" => "api/inits.md"],
    "References" => "references.md"
]
