name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
jobs:
  test:
    strategy:
      matrix:
        group:
          - Core
        julia-version: ["1.10"]
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      group: "${{ matrix.group }}"
      julia-version: "${{ matrix.julia-version }}"
      skip: "Pkg,TOML"
    secrets: "inherit"
